version: '3'

services:
  postgre:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=medods
      - POSTGRES_USER=test
      - POSTGRES_DB=testtask
    volumes:
      -pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ADDR=0.0.0.0:8080
      - POSTGRES_CONN=postgresql://test:medods@postgres:5432/testtask
      - JWT_KEY=medodsisthebest
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always
    ports:
      - 8081:8080